project:
  name: stock-market
  version: 0.0.1.ALPHA-RELEASE

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stock-market
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Burak1996!

  mail:
    host: smtp.gmail.com
    port: 465
    transport:
      protocol: smtp
    from:
      email: burakenesdemirr@gmail.com
      password: burakenes553409.
    default-encoding: UTF-8

stock-market:
  host: "http://127.0.0.1:8080"
  service:
    activate: "/email-activation/code/"
    reset-password: "/reset-password/"
  nodejs:
    twitter:
      uri: "http://localhost:4321/"
      mock-service: "http://localhost:3409/mock/get-tweets"
  redis:
    docker:
      host: "localhost"
      port: "6379"
